name: brain_age_1DCNN
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=3.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - attrs=23.1.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=6.0.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.7.4
  - certifi=2024.7.4
  - cffi=1.15.0
  - charset-normalizer=3.1.0
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - contourpy=1.0.5
  - cryptography=42.0.5
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.2.10
  - flit-core=3.8.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.9.0
  - hdf5=1.12.1
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.6.0
  - importlib_resources=5.12.0
  - ipykernel=6.15.0
  - ipython=8.13.2
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.6
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter_client=7.3.4
  - jupyter_core=5.3.0
  - jupyter_server=1.23.6
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.22.1
  - jupyterlab_widgets=3.0.7
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=10.0.1
  - libcurl=8.5.0
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libopenblas=0.3.20
  - libpng=1.6.39
  - libpq=12.17
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=12.3.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - littleutils=0.2.2
  - llvmlite=0.43.0
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=2.0.5
  - mpmath=1.3.0
  - munkres=1.1.4
  - nbclassic=1.0.0
  - nbclient=0.7.4
  - nbconvert-core=7.4.0
  - nbformat=5.8.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - nspr=4.33
  - nss=3.74
  - numba=0.60.0
  - numexpr=2.8.4
  - openssl=3.0.14
  - outdated=0.2.2
  - packaging=23.1
  - pandas=1.5.3
  - pandas-flavor=0.6.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pingouin=0.5.4
  - pip=22.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.5.0
  - ply=3.11
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=24.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python_abi=3.10
  - pytz=2023.3
  - pyzmq=25.0.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - scikit-learn=1.0.2
  - scipy=1.8.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - send2trash=1.8.2
  - setuptools=65.6.3
  - shap=0.42.1
  - sip=6.6.2
  - six=1.16.0
  - slicer=0.0.7
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.41.2
  - stack_data=0.6.2
  - statsmodels=0.13.5
  - tabulate=0.9.0
  - tbb=2021.8.0
  - terminado=0.17.1
  - threadpoolctl=3.1.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.1
  - traitlets=5.9.0
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2022a
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - wheel=0.37.1
  - widgetsnbextension=4.0.7
  - xarray=2023.12.0
  - xz=5.4.6
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - astor==0.8.1
      - async-timeout==4.0.2
      - bids-validator==1.14.0
      - blessed==1.20.0
      - click==8.1.3
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - formulaic==0.5.2
      - frozenlist==1.3.3
      - fsspec==2023.5.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - gpustat==1.1.1
      - greenlet==3.0.3
      - interface-meta==1.3.0
      - lightning-utilities==0.8.0
      - lxml==5.1.0
      - multidict==6.0.4
      - nibabel==5.2.0
      - nilearn==0.10.3
      - num2words==0.5.13
      - numpy==1.24.3
      - nvidia-ml-py==12.535.108
      - pathtools==0.1.2
      - pillow==9.5.0
      - protobuf==4.23.3
      - pyqt5-sip==12.11.0
      - pytorch-lightning==2.0.2
      - pyyaml==6.0
      - requests==2.30.0
      - sentry-sdk==1.27.0
      - setproctitle==1.3.2
      - smmap==5.0.0
      - sqlalchemy==2.0.27
      - torch==1.12.0+cu113
      - torchaudio==0.12.0+cu113
      - torchmetrics==0.11.4
      - torchvision==0.13.0+cu113
      - tqdm==4.65.0
      - urllib3==2.0.2
      - wandb==0.15.4
      - wrapt==1.16.0
      - yarl==1.9.2
