project: 'lightweight-brain-age-prediction'
group: 'schaefer_ts'
name: '7n100p_4-layers_out-128_no-scaling_final-dropout_ReduceLROnPlateau_double-patience'
tags: ['7n','100p','4 layers', 'no scaling', 'kernel=3', 'global pool', 'scale_after_conv=False', 'final dropout', 'ReduceLROnPlateau']
parameters:
    # dataset set-up
    schaefer_variant: '7n100p'
    corr_matrix: False
    shared_variants: ['7n100p','7n200p','7n500p','17n100p','17n200p','17n500p']
    additional_data_path: '../../data/schaefer/'
    heldout_set_name: 'heldout_test_set_100-500p.csv'
    # training set-up
    max_epochs: 175
    log_steps: 50
    patience: 15
    # model parameters
    in_channels: 100
    kernel_size: 3
    lr: 0.01
    depth: 4
    start_out: 128
    scale_dim: False
    scale_after_conv: False
    stride: 2
    weight_decay: 0.1
    dilation: 1
    conv_dropout: 0
    final_dropout: 0.5
    double_conv: False
    batch_norm: True